### ISSUE TITLE
Q: use as dependency

### ISSUE THREAD

**Issue by Dierk** [januslynd/sirocco#1]
is there a way to do a local installation like

> gradlew install

such that I can use it as a dependency?

**Comment by januslynd** [comment]
I've just added a commit. Now if you go to the `sirocco` root folder you can execute:

```
./gradlew :sirocco-core:install
```

That will install `sirocco-core` jar in your local maven repository. Then you can add the `sirocco-core` dependency in your own application.

**Comment by Dierk** [comment]
awesome! Thanks
Dierk
